### ISSUE TITLE
Indestructible blocks

### ISSUE THREAD

**Issue by Tygra** [AndrioCelos/Region-Vision#1]
With the new tshock update 4.3.11 (1.22) the plugin causes the blocks to be indestructible.
It just needs a ref update because of Main.tile
Don't know what did you complie it with, I tried but my visual 2013 couldn't handle it.
Would really appreciate an udpate, it's an essential plugin.

**Comment by AndrioCelos** [comment]
Thanks for the report.
A reference update didn't fix it. It's exciting in a way to have to actually fix something for a change before Ginny dies.

By the way, I'm using Visual Studio 2015. If I recall correctly, 2013 doesn't even support .NET 4.5.

**Comment by AndrioCelos** [comment]
`Terraria.Main.tile` now returns only a link to the tile data heap, so bad things were happening when this data was overwritten with the phantom tile.
I changed the `RegionVision.Region.setFakeTile` method to actually store copies of the real tiles, rather than just the links.
